<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Nina Flores" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>EDA Project</title>
    <meta name="generator" content="Hugo 0.60.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project1/">EDA Project</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          October 20, 2019
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p style="color:orange">
I obtained two datasets containing information about recent movies. As an avid movie goer, who is a proud AMC A-list member and an alumni of Moviepass (may it rest in peace), I was interested in seeing the relationships between various movie production companies, actors, budgets, genres, and success in the box office. Both datasets were obtained from kaggle (movies from Daniel Grijalva and IMDb from PrompCloud). The IMDb dataset contains information from 2006-2016 for the 1,000 most popular movies and 12 variables including rank, title, genre, description, actors, year, runtime, votes, rating, revenue, and metascore. The movies dataset contains 6820 movies in the dataset (220 movies per year, 1986-2016) and 15 variables, including budget, company, country, director, genre, gross revenue, rating, release date, runtime, IMDb score, votes, star, writer and year. I expect to see associations between the IMDb scores/metascores and the gross revenue generated by the films. I expect the movies with higher budgets to also be associated with higher revenues.
</p>
<pre class="r"><code>library(tidyverse)
library(reshape2)
IMD &lt;- read.csv(&quot;~/Downloads/IMDB-Movie-Data.csv&quot;)
IMD %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 1,000
## Variables: 12
## $ Rank               &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…
## $ Title              &lt;fct&gt; Guardians of the Galaxy, Prometheus, Split, S…
## $ Genre              &lt;fct&gt; &quot;Action,Adventure,Sci-Fi&quot;, &quot;Adventure,Mystery…
## $ Description        &lt;fct&gt; &quot;A group of intergalactic criminals are force…
## $ Director           &lt;fct&gt; James Gunn, Ridley Scott, M. Night Shyamalan,…
## $ Actors             &lt;fct&gt; &quot;Chris Pratt, Vin Diesel, Bradley Cooper, Zoe…
## $ Year               &lt;int&gt; 2014, 2012, 2016, 2016, 2016, 2016, 2016, 201…
## $ Runtime..Minutes.  &lt;int&gt; 121, 124, 117, 108, 123, 103, 128, 89, 141, 1…
## $ Rating             &lt;dbl&gt; 8.1, 7.0, 7.3, 7.2, 6.2, 6.1, 8.3, 6.4, 7.1, …
## $ Votes              &lt;int&gt; 757074, 485820, 157606, 60545, 393727, 56036,…
## $ Revenue..Millions. &lt;dbl&gt; 333.13, 126.46, 138.12, 270.32, 325.02, 45.13…
## $ Metascore          &lt;int&gt; 76, 65, 62, 59, 40, 42, 93, 71, 78, 41, 66, 7…</code></pre>
<pre class="r"><code>movies &lt;- read.csv(&quot;~/Downloads/movies.csv&quot;)
head(movies)</code></pre>
<pre><code>##     budget                                company country       director
## 1  8000000          Columbia Pictures Corporation     USA     Rob Reiner
## 2  6000000                     Paramount Pictures     USA    John Hughes
## 3 15000000                     Paramount Pictures     USA     Tony Scott
## 4 18500000 Twentieth Century Fox Film Corporation     USA  James Cameron
## 5  9000000                   Walt Disney Pictures     USA Randal Kleiser
## 6  6000000                                Hemdale      UK   Oliver Stone
##       genre     gross                     name rating   released runtime
## 1 Adventure  52287414              Stand by Me      R 1986-08-22      89
## 2    Comedy  70136369 Ferris Bueller&#39;s Day Off  PG-13 1986-06-11     103
## 3    Action 179800601                  Top Gun     PG 1986-05-16     110
## 4    Action  85160248                   Aliens      R 1986-07-18     137
## 5 Adventure  18564613  Flight of the Navigator     PG 1986-08-01      90
## 6     Drama 138530565                  Platoon      R 1987-02-06     120
##   score              star  votes        writer year
## 1   8.1       Wil Wheaton 299174  Stephen King 1986
## 2   7.8 Matthew Broderick 264740   John Hughes 1986
## 3   6.9        Tom Cruise 236909      Jim Cash 1986
## 4   8.4  Sigourney Weaver 540152 James Cameron 1986
## 5   6.9       Joey Cramer  36636 Mark H. Baker 1986
## 6   8.1     Charlie Sheen 317585  Oliver Stone 1986</code></pre>
<div id="tidying" class="section level2">
<h2>Tidying</h2>
<pre class="r"><code>IMD2 &lt;- IMD %&gt;% separate_rows(Actors, sep = &quot;, &quot;) %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 3,650
## Variables: 12
## $ Rank               &lt;int&gt; 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, …
## $ Title              &lt;fct&gt; Guardians of the Galaxy, Guardians of the Gal…
## $ Genre              &lt;fct&gt; &quot;Action,Adventure,Sci-Fi&quot;, &quot;Action,Adventure,…
## $ Description        &lt;fct&gt; &quot;A group of intergalactic criminals are force…
## $ Director           &lt;fct&gt; James Gunn, James Gunn, James Gunn, James Gun…
## $ Actors             &lt;chr&gt; &quot;Chris Pratt&quot;, &quot;Vin Diesel&quot;, &quot;Bradley Cooper&quot;…
## $ Year               &lt;int&gt; 2014, 2014, 2014, 2014, 2012, 2012, 2012, 201…
## $ Runtime..Minutes.  &lt;int&gt; 121, 121, 121, 121, 124, 124, 124, 124, 117, …
## $ Rating             &lt;dbl&gt; 8.1, 8.1, 8.1, 8.1, 7.0, 7.0, 7.0, 7.0, 7.3, …
## $ Votes              &lt;int&gt; 757074, 757074, 757074, 757074, 485820, 48582…
## $ Revenue..Millions. &lt;dbl&gt; 333.13, 333.13, 333.13, 333.13, 126.46, 126.4…
## $ Metascore          &lt;int&gt; 76, 76, 76, 76, 65, 65, 65, 65, 62, 62, 62, 6…</code></pre>
<pre class="r"><code>IMD3 &lt;- IMD2 %&gt;% separate_rows(Actors, sep = &quot;,&quot;)
IMD4 &lt;- IMD3 %&gt;% separate_rows(Genre, sep = &quot;,&quot;) %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 10,218
## Variables: 12
## $ Rank               &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, …
## $ Title              &lt;fct&gt; Guardians of the Galaxy, Guardians of the Gal…
## $ Genre              &lt;chr&gt; &quot;Action&quot;, &quot;Adventure&quot;, &quot;Sci-Fi&quot;, &quot;Action&quot;, &quot;A…
## $ Description        &lt;fct&gt; &quot;A group of intergalactic criminals are force…
## $ Director           &lt;fct&gt; James Gunn, James Gunn, James Gunn, James Gun…
## $ Actors             &lt;chr&gt; &quot;Chris Pratt&quot;, &quot;Chris Pratt&quot;, &quot;Chris Pratt&quot;, …
## $ Year               &lt;int&gt; 2014, 2014, 2014, 2014, 2014, 2014, 2014, 201…
## $ Runtime..Minutes.  &lt;int&gt; 121, 121, 121, 121, 121, 121, 121, 121, 121, …
## $ Rating             &lt;dbl&gt; 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, …
## $ Votes              &lt;int&gt; 757074, 757074, 757074, 757074, 757074, 75707…
## $ Revenue..Millions. &lt;dbl&gt; 333.13, 333.13, 333.13, 333.13, 333.13, 333.1…
## $ Metascore          &lt;int&gt; 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 7…</code></pre>
<pre class="r"><code>movies2 &lt;- movies %&gt;% separate(released, into = c(&quot;year&quot;, &quot;month&quot;, 
    &quot;day&quot;))</code></pre>
<pre><code>## Warning: Expected 3 pieces. Missing pieces filled with `NA` in 64 rows [62,
## 156, 173, 199, 204, 210, 211, 263, 378, 405, 408, 419, 423, 436, 440, 550,
## 587, 628, 629, 632, ...].</code></pre>
<pre class="r"><code>movie &lt;- movies2 %&gt;% rename(Title = name)
movie2 &lt;- movie %&gt;% rename(Year = year)
movie2$Year &lt;- as.numeric(as.character(movie2$Year))</code></pre>
<p style="color:orange">
Since these datasets were found from separate entities, it was important to first tidy each of them, so that they could easily be joined. In the IMD dataset, there were two variables that contained lists of information. These included the actors and genre categories. These lists were separated so that every genre had its own row as did every actor. A similar separation was used in the movies dataset to separate the day, month, and year of the released date into different columns. Having a year column will be important to the future joining steps. In the movies dataset, the “name” column was renamed to “Title” and “year” to “Year,” which was then converted to numeric rather than categorical to match the IMD set which will also be important for joining.
</p>
<pre class="r"><code>movies3 &lt;- movies2 %&gt;% pivot_longer(cols = c(&quot;year&quot;, &quot;month&quot;, 
    &quot;day&quot;), names_to = &quot;released&quot;)
movies4 &lt;- movies3 %&gt;% pivot_wider(names_from = &quot;released&quot;, values_from = &quot;value&quot;)</code></pre>
<p style="color:orange">
This code was used to demonstrate the ability to use the functions pivot_longer() and pivot_wider(). The first step put day, month, and year back into a single column, and the second separates them again.
</p>
</div>
<div id="joining" class="section level2">
<h2>Joining</h2>
<pre class="r"><code>doublefeature &lt;- full_join(movie2, IMD4, by = c(&quot;Title&quot;, &quot;Year&quot;)) %&gt;% 
    na.omit() %&gt;% glimpse()</code></pre>
<pre><code>## Warning: Column `Title` joining factors with different levels, coercing to
## character vector</code></pre>
<pre><code>## Observations: 6,600
## Variables: 26
## $ budget             &lt;dbl&gt; 4.00e+07, 4.00e+07, 4.00e+07, 4.00e+07, 4.00e…
## $ company            &lt;fct&gt; Touchstone Pictures, Touchstone Pictures, Tou…
## $ country            &lt;fct&gt; USA, USA, USA, USA, USA, USA, USA, USA, USA, …
## $ director           &lt;fct&gt; Christopher Nolan, Christopher Nolan, Christo…
## $ genre              &lt;fct&gt; Drama, Drama, Drama, Drama, Drama, Drama, Dra…
## $ gross              &lt;dbl&gt; 53089891, 53089891, 53089891, 53089891, 53089…
## $ Title              &lt;chr&gt; &quot;The Prestige&quot;, &quot;The Prestige&quot;, &quot;The Prestige…
## $ rating             &lt;fct&gt; PG-13, PG-13, PG-13, PG-13, PG-13, PG-13, PG-…
## $ Year               &lt;dbl&gt; 2006, 2006, 2006, 2006, 2006, 2006, 2006, 200…
## $ month              &lt;chr&gt; &quot;10&quot;, &quot;10&quot;, &quot;10&quot;, &quot;10&quot;, &quot;10&quot;, &quot;10&quot;, &quot;10&quot;, &quot;10…
## $ day                &lt;chr&gt; &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20…
## $ runtime            &lt;int&gt; 130, 130, 130, 130, 130, 130, 130, 130, 130, …
## $ score              &lt;dbl&gt; 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, …
## $ star               &lt;fct&gt; Christian Bale, Christian Bale, Christian Bal…
## $ votes              &lt;int&gt; 943597, 943597, 943597, 943597, 943597, 94359…
## $ writer             &lt;fct&gt; Jonathan Nolan, Jonathan Nolan, Jonathan Nola…
## $ Rank               &lt;int&gt; 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 6…
## $ Genre              &lt;chr&gt; &quot;Drama&quot;, &quot;Mystery&quot;, &quot;Sci-Fi&quot;, &quot;Drama&quot;, &quot;Myste…
## $ Description        &lt;fct&gt; &quot;Two stage magicians engage in competitive on…
## $ Director           &lt;fct&gt; Christopher Nolan, Christopher Nolan, Christo…
## $ Actors             &lt;chr&gt; &quot;Christian Bale&quot;, &quot;Christian Bale&quot;, &quot;Christia…
## $ Runtime..Minutes.  &lt;int&gt; 130, 130, 130, 130, 130, 130, 130, 130, 130, …
## $ Rating             &lt;dbl&gt; 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, …
## $ Votes              &lt;int&gt; 913152, 913152, 913152, 913152, 913152, 91315…
## $ Revenue..Millions. &lt;dbl&gt; 53.08, 53.08, 53.08, 53.08, 53.08, 53.08, 53.…
## $ Metascore          &lt;int&gt; 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 6…</code></pre>
<pre class="r"><code>doublefeature_1 &lt;- unite(doublefeature, &quot;Actors&quot;, &quot;Actors&quot;, &quot;star&quot;, 
    sep = &quot;, &quot;, remove = T) %&gt;% separate_rows(Actors, sep = &quot;, &quot;)</code></pre>
<p style="color:orange">
I used a full join on both “Title” and “Year” because I wanted my ending dataset include the movies that had information in both the movie and IMDb datasets. It was important to incorporate “Year” into the by function, because the dataset contains remakes that would otherwise be seen as the same movie, if I only joined by Title. I then removed all NA’s so that I would be left with a dataset that contained distinct movies with all the variables present in each dataset. Potential problems with this join is the high number of cases that were dropped, shrinking our sample size. However, I think it will be more meaningful for the comparisions if the movies have observations for every variable listed. Since the datasets had some overlapping variables, I combined them where they had differences label, like in the actors vs. stars columns.
</p>
</div>
<div id="summarizing" class="section level2">
<h2>Summarizing</h2>
<pre class="r"><code>doublefeature_2 &lt;- doublefeature_1 %&gt;% select(-c(&quot;director&quot;, 
    &quot;Rank&quot;, &quot;Rating&quot;, &quot;votes&quot;, &quot;genre&quot;))


doublefeature_3 &lt;- doublefeature_2 %&gt;% filter(budget != 0)
doublefeature_4 &lt;- doublefeature_3 %&gt;% mutate(Profit = (gross - 
    budget))


doublefeature_5 &lt;- doublefeature_4 %&gt;% filter(rating == c(&quot;R&quot;, 
    &quot;PG-13&quot;, &quot;PG&quot;, &quot;G&quot;))




df &lt;- doublefeature_5 %&gt;% group_by(Genre, rating) %&gt;% mutate(Actors = paste(unlist(Actors), 
    collapse = &quot;, &quot;)) %&gt;% distinct(df, Title, Genre, .keep_all = TRUE) %&gt;% 
    arrange(desc(Profit)) %&gt;% glimpse()</code></pre>
<pre><code>## Warning: Trying to compute distinct() for variables not found in the data:
## - `df`
## This is an error, but only a warning is raised for compatibility reasons.
## The following variables will be used:
## - Title
## - Genre</code></pre>
<pre><code>## Observations: 1,452
## Variables: 21
## Groups: Genre, rating [53]
## $ budget             &lt;dbl&gt; 2.37e+08, 2.37e+08, 2.37e+08, 1.50e+08, 1.50e…
## $ company            &lt;fct&gt; Twentieth Century Fox Film Corporation, Twent…
## $ country            &lt;fct&gt; UK, UK, UK, USA, USA, USA, USA, USA, USA, USA…
## $ gross              &lt;dbl&gt; 760507625, 760507625, 760507625, 652270625, 6…
## $ Title              &lt;chr&gt; &quot;Avatar&quot;, &quot;Avatar&quot;, &quot;Avatar&quot;, &quot;Jurassic World…
## $ rating             &lt;fct&gt; PG-13, PG-13, PG-13, PG-13, PG-13, PG-13, PG-…
## $ Year               &lt;dbl&gt; 2009, 2009, 2009, 2015, 2015, 2015, 2012, 200…
## $ month              &lt;chr&gt; &quot;12&quot;, &quot;12&quot;, &quot;12&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;05&quot;, &quot;07…
## $ day                &lt;chr&gt; &quot;18&quot;, &quot;18&quot;, &quot;18&quot;, &quot;12&quot;, &quot;12&quot;, &quot;12&quot;, &quot;04&quot;, &quot;18…
## $ runtime            &lt;int&gt; 162, 162, 162, 124, 124, 124, 143, 152, 152, …
## $ score              &lt;dbl&gt; 7.8, 7.8, 7.8, 7.0, 7.0, 7.0, 8.1, 9.0, 9.0, …
## $ Actors             &lt;chr&gt; &quot;Johnny Depp, Johnny Depp, Daniel Craig, Dani…
## $ writer             &lt;fct&gt; James Cameron, James Cameron, James Cameron, …
## $ Genre              &lt;chr&gt; &quot;Action&quot;, &quot;Fantasy&quot;, &quot;Adventure&quot;, &quot;Action&quot;, &quot;…
## $ Description        &lt;fct&gt; &quot;A paraplegic marine dispatched to the moon P…
## $ Director           &lt;fct&gt; James Cameron, James Cameron, James Cameron, …
## $ Runtime..Minutes.  &lt;int&gt; 162, 162, 162, 124, 124, 124, 143, 152, 152, …
## $ Votes              &lt;int&gt; 935408, 935408, 935408, 455169, 455169, 45516…
## $ Revenue..Millions. &lt;dbl&gt; 760.51, 760.51, 760.51, 652.18, 652.18, 652.1…
## $ Metascore          &lt;int&gt; 83, 83, 83, 59, 59, 59, 69, 82, 82, 82, 65, 6…
## $ Profit             &lt;dbl&gt; 523507625, 523507625, 523507625, 502270625, 5…</code></pre>
<pre class="r"><code>maxminmeanProf &lt;- doublefeature_5 %&gt;% summarize(maxprof = max(Profit), 
    minprof = min(Profit), mean(Profit))
maxminmeanProf</code></pre>
<pre><code>##     maxprof    minprof mean(Profit)
## 1 523507625 -176921900     31776255</code></pre>
<pre class="r"><code>maxProf &lt;- doublefeature_5 %&gt;% filter(Profit == 523507625) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Observations: 6
## Variables: 21
## $ budget             &lt;dbl&gt; 2.37e+08, 2.37e+08, 2.37e+08, 2.37e+08, 2.37e…
## $ company            &lt;fct&gt; Twentieth Century Fox Film Corporation, Twent…
## $ country            &lt;fct&gt; UK, UK, UK, UK, UK, UK
## $ gross              &lt;dbl&gt; 760507625, 760507625, 760507625, 760507625, 7…
## $ Title              &lt;chr&gt; &quot;Avatar&quot;, &quot;Avatar&quot;, &quot;Avatar&quot;, &quot;Avatar&quot;, &quot;Avat…
## $ rating             &lt;fct&gt; PG-13, PG-13, PG-13, PG-13, PG-13, PG-13
## $ Year               &lt;dbl&gt; 2009, 2009, 2009, 2009, 2009, 2009
## $ month              &lt;chr&gt; &quot;12&quot;, &quot;12&quot;, &quot;12&quot;, &quot;12&quot;, &quot;12&quot;, &quot;12&quot;
## $ day                &lt;chr&gt; &quot;18&quot;, &quot;18&quot;, &quot;18&quot;, &quot;18&quot;, &quot;18&quot;, &quot;18&quot;
## $ runtime            &lt;int&gt; 162, 162, 162, 162, 162, 162
## $ score              &lt;dbl&gt; 7.8, 7.8, 7.8, 7.8, 7.8, 7.8
## $ Actors             &lt;chr&gt; &quot;Sam Worthington&quot;, &quot;Sam Worthington&quot;, &quot;Sam Wo…
## $ writer             &lt;fct&gt; James Cameron, James Cameron, James Cameron, …
## $ Genre              &lt;chr&gt; &quot;Action&quot;, &quot;Fantasy&quot;, &quot;Adventure&quot;, &quot;Action&quot;, &quot;…
## $ Description        &lt;fct&gt; A paraplegic marine dispatched to the moon Pa…
## $ Director           &lt;fct&gt; James Cameron, James Cameron, James Cameron, …
## $ Runtime..Minutes.  &lt;int&gt; 162, 162, 162, 162, 162, 162
## $ Votes              &lt;int&gt; 935408, 935408, 935408, 935408, 935408, 935408
## $ Revenue..Millions. &lt;dbl&gt; 760.51, 760.51, 760.51, 760.51, 760.51, 760.51
## $ Metascore          &lt;int&gt; 83, 83, 83, 83, 83, 83
## $ Profit             &lt;dbl&gt; 523507625, 523507625, 523507625, 523507625, 5…</code></pre>
<pre class="r"><code>minProf &lt;- doublefeature_5 %&gt;% filter(Profit == -176921900) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Observations: 6
## Variables: 21
## $ budget             &lt;dbl&gt; 2.5e+08, 2.5e+08, 2.5e+08, 2.5e+08, 2.5e+08, …
## $ company            &lt;fct&gt; Walt Disney Pictures, Walt Disney Pictures, W…
## $ country            &lt;fct&gt; USA, USA, USA, USA, USA, USA
## $ gross              &lt;dbl&gt; 73078100, 73078100, 73078100, 73078100, 73078…
## $ Title              &lt;chr&gt; &quot;John Carter&quot;, &quot;John Carter&quot;, &quot;John Carter&quot;, …
## $ rating             &lt;fct&gt; PG-13, PG-13, PG-13, PG-13, PG-13, PG-13
## $ Year               &lt;dbl&gt; 2012, 2012, 2012, 2012, 2012, 2012
## $ month              &lt;chr&gt; &quot;03&quot;, &quot;03&quot;, &quot;03&quot;, &quot;03&quot;, &quot;03&quot;, &quot;03&quot;
## $ day                &lt;chr&gt; &quot;09&quot;, &quot;09&quot;, &quot;09&quot;, &quot;09&quot;, &quot;09&quot;, &quot;09&quot;
## $ runtime            &lt;int&gt; 132, 132, 132, 132, 132, 132
## $ score              &lt;dbl&gt; 6.6, 6.6, 6.6, 6.6, 6.6, 6.6
## $ Actors             &lt;chr&gt; &quot;Taylor Kitsch&quot;, &quot;Taylor Kitsch&quot;, &quot;Taylor Kit…
## $ writer             &lt;fct&gt; Andrew Stanton, Andrew Stanton, Andrew Stanto…
## $ Genre              &lt;chr&gt; &quot;Action&quot;, &quot;Sci-Fi&quot;, &quot;Adventure&quot;, &quot;Action&quot;, &quot;S…
## $ Description        &lt;fct&gt; &quot;Transported to Barsoom, a Civil War vet disc…
## $ Director           &lt;fct&gt; Andrew Stanton, Andrew Stanton, Andrew Stanto…
## $ Runtime..Minutes.  &lt;int&gt; 132, 132, 132, 132, 132, 132
## $ Votes              &lt;int&gt; 220667, 220667, 220667, 220667, 220667, 220667
## $ Revenue..Millions. &lt;dbl&gt; 73.06, 73.06, 73.06, 73.06, 73.06, 73.06
## $ Metascore          &lt;int&gt; 51, 51, 51, 51, 51, 51
## $ Profit             &lt;dbl&gt; -176921900, -176921900, -176921900, -17692190…</code></pre>
<p style="color:orange">
I used the select function to remove the redundant columns including: “director”, “Rank”, “Rating”, and “votes”. I then used the mutate function to create a new column for the profit, which was calculated by subtracting the gross earnings of the movie and subtracting the movie’s budget. Some movies did not report their budgets so I filtered those out to avoid reporting higher profits than there actually was. After generating the Profit, column I found that overall max and min profits to be $523,507,625 coming from Avatar and -$176,921,900 coming from John Carter. The overall mean for this new profit column is $31,776,255.
</p>
<pre class="r"><code>GenresOfInterest &lt;- c(&quot;Action&quot;, &quot;Comedy&quot;, &quot;Romance&quot;)
df_summaries &lt;- df %&gt;% filter(Genre %in% GenresOfInterest)

df_summaries %&gt;% summarize(n = n()) %&gt;% arrange(desc(n))</code></pre>
<pre><code>## # A tibble: 10 x 3
## # Groups:   Genre [3]
##    Genre   rating     n
##    &lt;chr&gt;   &lt;fct&gt;  &lt;int&gt;
##  1 Action  PG-13    154
##  2 Comedy  R         87
##  3 Comedy  PG-13     61
##  4 Action  R         58
##  5 Romance PG-13     31
##  6 Comedy  PG        29
##  7 Romance R         16
##  8 Action  PG        11
##  9 Comedy  G          7
## 10 Romance PG         2</code></pre>
<pre class="r"><code>df_summaries %&gt;% summarize_if(is.numeric, mean, na.rm = TRUE) %&gt;% 
    arrange(desc(Profit))</code></pre>
<pre><code>## # A tibble: 10 x 12
## # Groups:   Genre [3]
##    Genre rating budget  gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;            &lt;dbl&gt;  &lt;dbl&gt;
##  1 Come… PG     1.11e8 1.87e8 2013.   100.   7.06            100.  1.86e5
##  2 Acti… PG     1.29e8 2.03e8 2013.   104.   7.24            104.  2.40e5
##  3 Come… G      1.52e8 2.25e8 2010.   105.   7.27            105.  2.87e5
##  4 Come… R      3.07e7 6.79e7 2013.   108.   6.66            108.  1.93e5
##  5 Acti… PG-13  1.32e8 1.58e8 2012.   122.   6.61            122.  2.96e5
##  6 Come… PG-13  5.17e7 7.76e7 2012.   107.   6.43            107.  1.46e5
##  7 Roma… R      3.85e7 6.28e7 2012.   115.   6.48            115.  1.88e5
##  8 Roma… PG     1.65e7 3.64e7 2012.    89.5  6                89.5 5.01e4
##  9 Acti… R      5.09e7 6.69e7 2012.   112.   6.83            112.  2.14e5
## 10 Roma… PG-13  4.27e7 5.63e7 2011.   112.   6.65            113.  1.72e5
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;dbl&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>df_summaries %&gt;% summarize_if(is.numeric, max, na.rm = TRUE)</code></pre>
<pre><code>## # A tibble: 10 x 12
## # Groups:   Genre [3]
##    Genre rating budget  gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt;            &lt;int&gt;  &lt;int&gt;
##  1 Acti… PG     1.90e8 3.36e8  2016     140   8.1              140 5.24e5
##  2 Acti… PG-13  3.00e8 7.61e8  2016     169   9                169 1.79e6
##  3 Acti… R      1.50e8 3.63e8  2016     162   8.1              162 6.33e5
##  4 Come… G      2.00e8 4.15e8  2013     117   8.3              117 5.87e5
##  5 Come… PG     2.60e8 4.86e8  2016     125   8.3              125 7.22e5
##  6 Come… PG-13  2.25e8 1.91e8  2016     128   8.2              128 4.32e5
##  7 Come… R      1.00e8 3.63e8  2016     180   8.2              180 8.65e5
##  8 Roma… PG     3.00e7 5.87e7  2016      90   6.5               90 8.40e4
##  9 Roma… PG-13  1.50e8 1.91e8  2016     166   7.8              166 4.85e5
## 10 Roma… R      1.00e8 1.66e8  2016     146   7.8              146 5.64e5
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;int&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>df_summaries %&gt;% summarize_if(is.numeric, min, na.rm = TRUE)</code></pre>
<pre><code>## # A tibble: 10 x 12
## # Groups:   Genre [3]
##    Genre rating budget  gross  Year runtime score Runtime..Minute… Votes
##    &lt;chr&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt;            &lt;int&gt; &lt;int&gt;
##  1 Acti… PG     4.00e7 9.34e7  2008      91   6.2               91 89791
##  2 Acti… PG-13  1.00e7 3.77e6  2006      85   4.3               85 11555
##  3 Acti… R      1.20e7 1.22e5  2006      88   5.2               88 31194
##  4 Come… G      9.00e7 1.04e8  2006      96   6.2               96 95480
##  5 Come… PG     3.00e6 1.40e7  2006      87   5.3               87 16164
##  6 Come… PG-13  3.80e6 6.85e5  2006      87   1.9               87  5908
##  7 Come… R      2.50e6 1.82e6  2006      83   4.3               83 26521
##  8 Roma… PG     3.00e6 1.40e7  2009      89   5.5               89 16164
##  9 Roma… PG-13  3.80e6 1.02e6  2006      88   5.2               88  5908
## 10 Roma… R      2.00e6 3.59e6  2008      90   4.1               90 25903
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;int&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>what &lt;- df_summaries %&gt;% filter(score == 1.9) %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 1
## Variables: 21
## Groups: Genre, rating [13]
## $ budget             &lt;dbl&gt; 2e+07
## $ company            &lt;fct&gt; Lionsgate
## $ country            &lt;fct&gt; USA
## $ gross              &lt;dbl&gt; 14190901
## $ Title              &lt;chr&gt; &quot;Disaster Movie&quot;
## $ rating             &lt;fct&gt; PG-13
## $ Year               &lt;dbl&gt; 2008
## $ month              &lt;chr&gt; &quot;08&quot;
## $ day                &lt;chr&gt; &quot;29&quot;
## $ runtime            &lt;int&gt; 87
## $ score              &lt;dbl&gt; 1.9
## $ Actors             &lt;chr&gt; &quot;Anne Hathaway, Anne Hathaway, Anne Hathaway,…
## $ writer             &lt;fct&gt; Jason Friedberg
## $ Genre              &lt;chr&gt; &quot;Comedy&quot;
## $ Description        &lt;fct&gt; &quot;Over the course of one evening, an unsuspect…
## $ Director           &lt;fct&gt; Jason Friedberg
## $ Runtime..Minutes.  &lt;int&gt; 87
## $ Votes              &lt;int&gt; 77207
## $ Revenue..Millions. &lt;dbl&gt; 14.17
## $ Metascore          &lt;int&gt; 15
## $ Profit             &lt;dbl&gt; -5809099</code></pre>
<p style="color:orange">
I was interested in comparing genres together, however, that is difficult to do when there are 57 different categories. I used filter to narrow these down to the three I found most interesting: Action, Comedy, and Romance. I also filtered out ratings that weren’t G, PG, PG-13, and R because the datasets were not uniform in what they determined to be unrated vs. not-rated etc. This filtering was important because I wanted to group by genre and rating for summary statistics. I first looked at the count and Action movies across the boards overwhelm the amounts of movies in Romance and Comedy. Action-PG-13 movies alone was almost double and other of the genre-rating combinations with 154 films. Notably, a bulk of comedies were rated R at 87. I looked at the mean, the maximum, and the minimum for each rating of each genre and arranged by the maximum mean profit. The highest maxmium mean profit came from PG comedies at $76,128,321and the lowest came from PG-13 romances at $13,578,523. By looking at the minimum values across the numeric variables in the grouping, I found that the lowest IMDb score came from a PG-13 comedy at 1.9. The title of that movie ended up being “Disaster Movie” which seemed fitting.
</p>
</div>
<div id="more-summarizing" class="section level2">
<h2>More summarizing</h2>
<pre class="r"><code>df2 &lt;- doublefeature_5 %&gt;% group_by(Actors) %&gt;% mutate(Genre = paste(unlist(Genre), 
    collapse = &quot;, &quot;)) %&gt;% distinct(df, Title, Actors, .keep_all = TRUE)</code></pre>
<pre><code>## Warning: Trying to compute distinct() for variables not found in the data:
## - `df`
## This is an error, but only a warning is raised for compatibility reasons.
## The following variables will be used:
## - Title
## - Actors</code></pre>
<pre class="r"><code>ActorsOfInterest &lt;- c(&quot;Meryl Streep&quot;, &quot;Nicolas Cage&quot;, &quot;Tom Cruise&quot;, 
    &quot;Tom Hanks&quot;, &quot;Nicole Kidman&quot;, &quot;Leonardo DiCaprio&quot;, &quot;Denzel Washington&quot;, 
    &quot;Julia Roberts&quot;, &quot;Morgan Freeman&quot;, &quot;Johnny Depp&quot;, &quot;Angelina Jolie&quot;, 
    &quot;Reese Witherspoon&quot;)
df_summaries_Act &lt;- df2 %&gt;% filter(Actors %in% ActorsOfInterest)

df_summaries_Act %&gt;% summarize(n = n()) %&gt;% arrange(desc(n))</code></pre>
<pre><code>## # A tibble: 12 x 2
##    Actors                n
##    &lt;chr&gt;             &lt;int&gt;
##  1 Johnny Depp          10
##  2 Denzel Washington     8
##  3 Tom Hanks             8
##  4 Angelina Jolie        6
##  5 Leonardo DiCaprio     6
##  6 Morgan Freeman        6
##  7 Tom Cruise            5
##  8 Meryl Streep          4
##  9 Reese Witherspoon     3
## 10 Nicolas Cage          2
## 11 Nicole Kidman         2
## 12 Julia Roberts         1</code></pre>
<p style="color:orange">
Now let’s look at some specific actors and see how their movies size up. I compiled a list of 12 of my favorite actors, and actors I thought would be prominent in the 10 year span that these movie datasets were generated from. By counting the number of roles an actor had, and arranging in descending order, it is easy to see that Johnny Depp, Denzel Washington, and Tom Hanks were very busy in these years with 10, 8, and 8 films reported respectively.
</p>
<pre class="r"><code>df_summaries_Act %&gt;% summarize_if(is.numeric, mean, na.rm = TRUE) %&gt;% 
    arrange(desc(Profit))</code></pre>
<pre><code>## # A tibble: 12 x 11
##    Actors budget  gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;            &lt;dbl&gt;  &lt;dbl&gt;
##  1 Reese… 5.17e7 1.21e8 2014     107.  6.83             109. 1.03e5
##  2 Leona… 1.00e8 1.45e8 2010.    152.  8.18             152. 9.11e5
##  3 Tom H… 8.59e7 1.25e8 2013     127.  7.2              127. 2.56e5
##  4 Meryl… 4.28e7 8.01e7 2012.    108.  6.78             108. 1.11e5
##  5 Angel… 1.16e8 1.48e8 2011.    106.  7.1              106. 2.44e5
##  6 Morga… 4.85e7 7.76e7 2011.    107.  6.83             107. 2.43e5
##  7 Denze… 6.56e7 9.27e7 2011.    130.  7.21             130. 2.15e5
##  8 Julia… 2.70e7 4.10e7 2016      98   6.5               98  6.87e4
##  9 Nicol… 7.00e7 8.19e7 2008.    116.  6.45             116. 3.24e5
## 10 Johnn… 1.60e8 1.70e8 2011.    125.  6.75             129. 2.89e5
## 11 Tom C… 1.31e8 1.23e8 2011.    125   7.24             125  3.57e5
## 12 Nicol… 1.55e8 5.98e7 2008.    139   6.35             139  1.31e5
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;dbl&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>df_summaries_Act %&gt;% summarize_if(is.numeric, max, na.rm = TRUE)</code></pre>
<pre><code>## # A tibble: 12 x 11
##    Actors budget  gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt;            &lt;int&gt;  &lt;int&gt;
##  1 Angel… 1.80e8 2.41e8  2016     141   7.8              141 3.30e5
##  2 Denze… 1.00e8 1.30e8  2016     157   7.8              157 3.38e5
##  3 Johnn… 3.00e8 4.23e8  2016     169   7.4              169 5.52e5
##  4 Julia… 2.70e7 4.10e7  2016      98   6.5               98 6.87e4
##  5 Leona… 1.60e8 2.93e8  2013     180   8.8              180 1.58e6
##  6 Meryl… 5.20e7 1.44e8  2016     125   7.8              125 1.53e5
##  7 Morga… 7.50e7 1.35e8  2016     119   7.8              119 3.53e5
##  8 Nicol… 1.10e8 1.16e8  2010     117   7.7              117 4.57e5
##  9 Nicol… 1.80e8 7.01e7  2008     165   6.6              165 1.55e5
## 10 Reese… 7.50e7 2.70e8  2016     115   7.1              115 1.54e5
## 11 Tom C… 1.78e8 2.09e8  2014     132   7.9              132 4.72e5
## 12 Tom H… 2.00e8 4.15e8  2016     172   8.3              172 5.87e5
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;int&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>df_summaries_Act %&gt;% summarize_if(is.numeric, min, na.rm = TRUE)</code></pre>
<pre><code>## # A tibble: 12 x 11
##    Actors budget  gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt;            &lt;int&gt;  &lt;int&gt;
##  1 Angel… 5.50e7 3.57e7  2008      92   6.4               92  89791
##  2 Denze… 2.40e7 5.76e7  2006      98   6.8               98  50953
##  3 Johnn… 5.00e7 2.30e7  2006     100   6.2              108  57207
##  4 Julia… 2.70e7 4.10e7  2016      98   6.5               98  68654
##  5 Leona… 7.00e7 3.94e7  2006     128   7.1              128 182305
##  6 Meryl… 2.90e7 2.10e7  2008      87   6                 87  31776
##  7 Morga… 1.90e7 2.03e7  2006      89   5.9               89 100702
##  8 Nicol… 3.00e7 4.81e7  2007     114   5.2              114 190673
##  9 Nicol… 1.30e8 4.96e7  2007     113   6.1              113 106115
## 10 Reese… 1.50e7 3.79e7  2012      97   6.3              103  60545
## 11 Tom C… 6.00e7 8.01e7  2006     113   6.9              113 250811
## 12 Tom H… 3.00e7 4.20e6  2006      96   6.1               96  26521
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;int&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>Reese &lt;- df2 %&gt;% filter(Actors == &quot;Reese Witherspoon&quot;) %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 3
## Variables: 21
## Groups: Actors [1]
## $ budget             &lt;dbl&gt; 6.5e+07, 1.5e+07, 7.5e+07
## $ company            &lt;fct&gt; Overbrook Entertainment, Bob Industries, Dent…
## $ country            &lt;fct&gt; USA, USA, USA
## $ gross              &lt;dbl&gt; 54760791, 37880356, 270329045
## $ Title              &lt;chr&gt; &quot;This Means War&quot;, &quot;Wild&quot;, &quot;Sing&quot;
## $ rating             &lt;fct&gt; PG-13, R, PG
## $ Year               &lt;dbl&gt; 2012, 2014, 2016
## $ month              &lt;chr&gt; &quot;02&quot;, &quot;12&quot;, &quot;12&quot;
## $ day                &lt;chr&gt; &quot;17&quot;, &quot;19&quot;, &quot;21&quot;
## $ runtime            &lt;int&gt; 97, 115, 108
## $ score              &lt;dbl&gt; 6.3, 7.1, 7.1
## $ Actors             &lt;chr&gt; &quot;Reese Witherspoon&quot;, &quot;Reese Witherspoon&quot;, &quot;Re…
## $ writer             &lt;fct&gt; Timothy Dowling, Nick Hornby, Garth Jennings
## $ Genre              &lt;chr&gt; &quot;Action, Romance, Comedy, Action, Romance, Co…
## $ Description        &lt;fct&gt; &quot;Two top CIA operatives wage an epic battle a…
## $ Director           &lt;fct&gt; McG, Jean-Marc Vallée, Christophe Lourdelet
## $ Runtime..Minutes.  &lt;int&gt; 103, 115, 108
## $ Votes              &lt;int&gt; 154400, 95553, 60545
## $ Revenue..Millions. &lt;dbl&gt; 54.76, 37.88, 270.32
## $ Metascore          &lt;int&gt; 31, 76, 59
## $ Profit             &lt;dbl&gt; -10239209, 22880356, 195329045</code></pre>
<p style="color:orange">
Reese Witherspoon had the highest mean profit associated with her movies at $69,323,397– over double the average mean profit for all movies found earlier. These profits are coming from the movies: This Means War (2012), Wild (2014), and Sing(2016), with Sing really driving this average upwards. Notably, Leonardo DiCaprio starred in the movies with the highest average score (8.18) and metascore (72.5) – which may help understand his Oscar in 2016. He also was in movies associated with the highest budgets on average at $100,000,000, which also may be translating to these higher scores.
</p>
<pre class="r"><code>df_summaries_Act %&gt;% mutate(gross = log(gross), budget = log(budget), 
    Profit = gross - budget) %&gt;% summarize_if(is.numeric, mean, 
    na.rm = TRUE) %&gt;% arrange(desc(Profit))</code></pre>
<pre><code>## # A tibble: 12 x 11
##    Actors budget gross  Year runtime score Runtime..Minute…  Votes
##    &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;            &lt;dbl&gt;  &lt;dbl&gt;
##  1 Reese…   17.5  18.2 2014     107.  6.83             109. 1.03e5
##  2 Denze…   17.9  18.3 2011.    130.  7.21             130. 2.15e5
##  3 Julia…   17.1  17.5 2016      98   6.5               98  6.87e4
##  4 Morga…   17.6  17.9 2011.    107.  6.83             107. 2.43e5
##  5 Meryl…   17.5  17.9 2012.    108.  6.78             108. 1.11e5
##  6 Nicol…   17.9  18.1 2008.    116.  6.45             116. 3.24e5
##  7 Leona…   18.4  18.6 2010.    152.  8.18             152. 9.11e5
##  8 Angel…   18.5  18.7 2011.    106.  7.1              106. 2.44e5
##  9 Tom C…   18.6  18.6 2011.    125   7.24             125  3.57e5
## 10 Tom H…   18.1  18.0 2013     127.  7.2              127. 2.56e5
## 11 Johnn…   18.7  18.6 2011.    125.  6.75             129. 2.89e5
## 12 Nicol…   18.8  17.9 2008.    139   6.35             139  1.31e5
## # … with 3 more variables: Revenue..Millions. &lt;dbl&gt;, Metascore &lt;dbl&gt;,
## #   Profit &lt;dbl&gt;</code></pre>
<pre class="r"><code>df2 %&gt;% filter(Actors == &quot;Nicole Kidman&quot;) %&gt;% glimpse()</code></pre>
<pre><code>## Observations: 2
## Variables: 21
## Groups: Actors [1]
## $ budget             &lt;dbl&gt; 1.8e+08, 1.3e+08
## $ company            &lt;fct&gt; New Line Cinema, Twentieth Century Fox Film C…
## $ country            &lt;fct&gt; UK, UK
## $ gross              &lt;dbl&gt; 70107728, 49554002
## $ Title              &lt;chr&gt; &quot;The Golden Compass&quot;, &quot;Australia&quot;
## $ rating             &lt;fct&gt; PG-13, PG-13
## $ Year               &lt;dbl&gt; 2007, 2008
## $ month              &lt;chr&gt; &quot;12&quot;, &quot;11&quot;
## $ day                &lt;chr&gt; &quot;07&quot;, &quot;26&quot;
## $ runtime            &lt;int&gt; 113, 165
## $ score              &lt;dbl&gt; 6.1, 6.6
## $ Actors             &lt;chr&gt; &quot;Nicole Kidman&quot;, &quot;Nicole Kidman&quot;
## $ writer             &lt;fct&gt; Chris Weitz, Stuart Beattie
## $ Genre              &lt;chr&gt; &quot;Adventure, Fantasy, Family, Adventure, Fanta…
## $ Description        &lt;fct&gt; &quot;In a parallel universe, young Lyra Belacqua …
## $ Director           &lt;fct&gt; Chris Weitz, Baz Luhrmann
## $ Runtime..Minutes.  &lt;int&gt; 113, 165
## $ Votes              &lt;int&gt; 155078, 106115
## $ Revenue..Millions. &lt;dbl&gt; 70.08, 49.55
## $ Metascore          &lt;int&gt; 51, 53
## $ Profit             &lt;dbl&gt; -109892272, -80445998</code></pre>
<p style="color:orange">
Even if we transform the budgets and gross revenues, Reese Witherspoon is still featured at the top of profits. Nicole Kidman is found at the bottom at $10,236,936 average profits from the two movies Australia (2007) and The Golden Compass (2008). These movies also had the lowest average IMDb score at 6.35, but the lowest average metascore belongs to Nicolas Cage at 50.5.
</p>
</div>
<div id="displaying" class="section level2">
<h2>Displaying</h2>
<pre class="r"><code>doublefeature_2 %&gt;% summarize(Metacritic_Score = mean(Metascore))</code></pre>
<pre><code>##   Metacritic_Score
## 1         58.64727</code></pre>
<pre class="r"><code>doublefeature_2$Metacritic_Score &lt;- ifelse(doublefeature_2$Metascore &lt; 
    mean(doublefeature_2$Metascore), &quot;Low (Below the Mean)&quot;, 
    &quot;High(Above the Mean)&quot;)

doublefeature_3 &lt;- doublefeature_2 %&gt;% filter(rating == c(&quot;R&quot;, 
    &quot;PG-13&quot;, &quot;PG&quot;, &quot;G&quot;))



ggplot(doublefeature_3, aes(x = rating, y = Revenue..Millions., 
    fill = Metacritic_Score)) + geom_bar(stat = &quot;summary&quot;, fun.y = &quot;mean&quot;, 
    position = &quot;dodge&quot;) + geom_errorbar(stat = &quot;summary&quot;, position = &quot;dodge&quot;) + 
    xlab(&quot;Rating&quot;) + ggtitle(&quot;Mean Revenue Per Rating Category&quot;) + 
    scale_fill_brewer(palette = &quot;Spectral&quot;) + theme_dark()</code></pre>
<img src="/Project1_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" />
<p style="color:orange">
For this first graph, a new categorical variable was generated based on whether or not a metacritic score was above or below the average score of 58.64727. I chose to use mean because this variable was normally distributed. I then selected for only the ratings “G”,“PG”, “PG-13”,and R&quot; because these are the predominant rating categories, and there was not a uniform definition/criteria for “Unrated”“,”Not Rated“, and the other categories. I then created a bar chart that displays the average revenue in millions for both the high and low metascore among each classification of rating. I found this graph to be interesting, because it makes logical sense. Across all the rating categories, the more highly rated movies genrated the most money. This implies that people are more inclined to see movies that are more highly rated. Furthermore, the movies with the fewest age restiction generate the most money and as age restictions become more strict, less money is made. This is something that could be further studied among even more movies. If this holds true, directors and writers may have second-thoughts about a few choice scenes or words that causes a movie to be categorized as R rather than PG-13.
</p>
<img src="/Project1_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" />
<p style="color:orange">
This second graph focused on the amount of movies generated for two notoriously popular movie categories, Action and Comedy, over a year timespan. The summer months were the most popular for generating movies, which is likely targeting greater freetime among those who get summers off. The bulk of Action movies are released between May and August. There is a large surge in comedy movies for June. You can also see a greater pick up in movies put out during November and December which is typically referred to as “Oscar season.” An overall trend for this graph is that there are more Action movies released than comedy for a majority of the months.
</p>
<pre class="r"><code>df_vis %&gt;% ggplot(aes(budget, gross, color = Genre)) + geom_point() + 
    scale_color_brewer(palette = &quot;Spectral&quot;) + theme_dark() + 
    xlab(&quot;Budget&quot;) + ggtitle(&quot;Gross Revenue vs. Budget&quot;) + ylab(&quot;Revenue&quot;) + 
    scale_x_log10() + scale_y_log10() + geom_smooth(method = lm)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-12-1.png" width="768" style="display: block; margin: auto;" /></p>
<p style="color:orange">
This graph essentially gives a visualization to the profits from these movies. The x-axis the composed of the budgets reported for the movies and the y-axis is gross revenue generated. I focused on the Action and Comdey categories once again. An overall trend seems to be a higher revenue generated by movies with highest budgets. There is a large number of comedy budgets that receive a lower funding comparatively, but are still doing well in the box offices. Action movies tending to cost more makes sense when you think about stunt doubles, more skilled production teams/equipment, and special effects adding to the cost. I added the linear regression line because it helps visualize that among a majority of the budgets, Comedy is generating more revenue than Action movies.
</p>
<pre class="r"><code>doublefeature_6 &lt;- doublefeature_5 %&gt;% mutate(Actors = paste(unlist(Actors), 
    collapse = &quot;, &quot;), Genre = paste(unlist(Genre), collapse = &quot;, &quot;)) %&gt;% 
    distinct(doublefeature_6, Title, writer, .keep_all = TRUE)</code></pre>
<pre><code>## Warning: Trying to compute distinct() for variables not found in the data:
## - `doublefeature_6`
## This is an error, but only a warning is raised for compatibility reasons.
## The following variables will be used:
## - Title
## - writer</code></pre>
<pre class="r"><code>mycor &lt;- doublefeature_6[, c(1, 4, 17, 11, 18, 20, 21)]
head(mycor)</code></pre>
<pre><code>##     budget     gross Runtime..Minutes. score  Votes Metascore    Profit
## 1 4.00e+07  53089891               130   8.5 913152        66  13089891
## 2 9.00e+07 132384315               151   8.5 937414        85  42384315
## 3 2.25e+08 423315812               151   7.3 552027        53 198315812
## 4 3.50e+07  10144010                96   7.3 199193        51 -24855990
## 5 1.50e+08 167445960               144   8.0 495106        80  17445960
## 6 4.00e+07  50866635               139   7.8 247926        68  10866635</code></pre>
<pre class="r"><code>cormat &lt;- round(cor(mycor), 2)
head(cormat)</code></pre>
<pre><code>##                   budget gross Runtime..Minutes. score Votes Metascore
## budget              1.00  0.69              0.41  0.08  0.42      0.02
## gross               0.69  1.00              0.32  0.27  0.61      0.25
## Runtime..Minutes.   0.41  0.32              1.00  0.34  0.45      0.21
## score               0.08  0.27              0.34  1.00  0.59      0.73
## Votes               0.42  0.61              0.45  0.59  1.00      0.45
## Metascore           0.02  0.25              0.21  0.73  0.45      1.00
##                   Profit
## budget              0.11
## gross               0.80
## Runtime..Minutes.   0.10
## score               0.31
## Votes               0.48
## Metascore           0.33</code></pre>
<pre class="r"><code>melted_cormat &lt;- melt(cormat)
head(melted_cormat)</code></pre>
<pre><code>##                Var1   Var2 value
## 1            budget budget  1.00
## 2             gross budget  0.69
## 3 Runtime..Minutes. budget  0.41
## 4             score budget  0.08
## 5             Votes budget  0.42
## 6         Metascore budget  0.02</code></pre>
<pre class="r"><code># Get lower triangle of the correlation matrix
get_lower_tri &lt;- function(cormat) {
    cormat[upper.tri(cormat)] &lt;- NA
    return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri &lt;- function(cormat) {
    cormat[lower.tri(cormat)] &lt;- NA
    return(cormat)
}


upper_tri &lt;- get_upper_tri(cormat)
upper_tri</code></pre>
<pre><code>##                   budget gross Runtime..Minutes. score Votes Metascore
## budget                 1  0.69              0.41  0.08  0.42      0.02
## gross                 NA  1.00              0.32  0.27  0.61      0.25
## Runtime..Minutes.     NA    NA              1.00  0.34  0.45      0.21
## score                 NA    NA                NA  1.00  0.59      0.73
## Votes                 NA    NA                NA    NA  1.00      0.45
## Metascore             NA    NA                NA    NA    NA      1.00
## Profit                NA    NA                NA    NA    NA        NA
##                   Profit
## budget              0.11
## gross               0.80
## Runtime..Minutes.   0.10
## score               0.31
## Votes               0.48
## Metascore           0.33
## Profit              1.00</code></pre>
<pre class="r"><code>melted_cormat &lt;- melt(upper_tri, na.rm = TRUE)



Heatmap &lt;- melted_cormat %&gt;% ggplot(aes(Var2, Var1, fill = value)) + 
    geom_tile(color = &quot;black&quot;) + scale_fill_gradient2(low = &quot;black&quot;, 
    high = &quot;orange&quot;, mid = &quot;white&quot;, midpoint = 0, limit = c(-1, 
        1), space = &quot;Lab&quot;, name = &quot;Pearson\nCorrelation&quot;) + theme_dark() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, 
        hjust = 1)) + coord_fixed() + geom_text(aes(Var2, Var1, 
    label = value), color = &quot;black&quot;, size = 3)

Heatmap + theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
    panel.grid.major = element_blank(), panel.border = element_blank(), 
    panel.background = element_rect(fill = &quot;dark grey&quot;), axis.ticks = element_blank(), 
    legend.justification = c(1, 0), legend.position = c(0.6, 
        0.7), legend.direction = &quot;horizontal&quot;) + guides(fill = guide_colorbar(barwidth = 7, 
    barheight = 1, title.position = &quot;top&quot;, title.hjust = 0.5))</code></pre>
<img src="/Project1_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" />
<p style="color:orange">
This last graph is a correlation heat matrix for all the numeric variables. I generated it by selecting my numeric variables and then generating their correlation matrix. For easier viewing, I removed the upper triangle, since it is just a reflection of the lower triangle. The strongest correlations were between Profit and gross at .8, score and Metascore at .73, and budget and gross revenue at .69. These relationships have been prominent throughout this analysis and the heat map does a good job of illustrating the strength of these. I have largely ignored runtime throughout this analysis, because I orginally thought it would be irrelevant. However, this heat map reveals its correlation with budget. This relationship makes sense, because a larger budget will be able to pay for more days of filming and for larger production teams, which can help translate to a movie with more minutes.
</p>
</div>
<div id="dimensionality-reduction" class="section level2">
<h2>Dimensionality Reduction</h2>
<pre class="r"><code>doublefeature_6 %&gt;% select(c(gross, budget, Metascore, score)) %&gt;% 
    cor()</code></pre>
<pre><code>##               gross     budget  Metascore     score
## gross     1.0000000 0.68858676 0.25012826 0.2743685
## budget    0.6885868 1.00000000 0.01525247 0.0793230
## Metascore 0.2501283 0.01525247 1.00000000 0.7272151
## score     0.2743685 0.07932300 0.72721508 1.0000000</code></pre>
<pre class="r"><code>dr_pca &lt;- doublefeature_6 %&gt;% select(c(gross, budget, Metascore, 
    score)) %&gt;% mutate(gross = sqrt(gross), budget = sqrt(budget)) %&gt;% 
    scale() %&gt;% princomp()

summary(dr_pca, loadings = T)</code></pre>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4
## Standard deviation     1.4188371 1.2079506 0.53782538 0.48142135
## Proportion of Variance 0.5041233 0.3654013 0.07243598 0.05803934
## Cumulative Proportion  0.5041233 0.8695247 0.94196066 1.00000000
## 
## Loadings:
##           Comp.1 Comp.2 Comp.3 Comp.4
## gross      0.546  0.427  0.436  0.574
## budget     0.404  0.618 -0.364 -0.568
## Metascore  0.506 -0.492  0.504 -0.498
## score      0.532 -0.440 -0.651  0.316</code></pre>
<pre class="r"><code>eigval &lt;- dr_pca$sdev^2  #square to convert SDs to eigenvalues
varprop = round(eigval/sum(eigval), 2)  #proportion of var explained by each PC
ggplot() + geom_bar(aes(y = varprop, x = 1:4), stat = &quot;identity&quot;) + 
    xlab(&quot;&quot;) + geom_path(aes(y = varprop, x = 1:4)) + geom_text(aes(x = 1:4, 
    y = varprop, label = round(varprop, 2)), vjust = 1, col = &quot;white&quot;, 
    size = 5) + scale_y_continuous(breaks = seq(0, 0.6, 0.2), 
    labels = scales::percent) + scale_x_continuous(breaks = 1:10)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-14-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># justified to keep two</code></pre>
<p style="color:orange">
In the first step of this dimensionality reduction, I put both actors and genres back into their original list form so that each movie would only be counted once. I selected Metascore, IMDb score, budget, and gross revenue. I then viewed the correlations of these variables. Gross revenue and budget were most strongly correlated. I then prepared the data for the principal component analysis. First, I took the square root of both the budget and revenue columns since these two were strongly positively skewed. I then scaled all four columns. I then used princomp() on my scaled values in order to calculate the covariance matrix and eigenvectors. Viewing these values, it looks like PC1 represents the general popularity of a film. Each variable is positive and similar in magnitude with score and gross revenue being the closest. In general, movies scoring high on PC1 will have high budgets, high scores, and high gross revenues, while the lowest scores will be opposite on all accounts. PC2 on the other hand is a general budget and revenue vs. scoring axis. On PC2 a higher score means a higher budget and gross revenue with lower viewer/critic scores. Lower scores on this axis have lower budgets and revenues, but higher scores. PC3 is a Metascore vs. score axis. Higher scores here mean higher critic ratings and lower viewer ratings. PC4 is a budget vs gross revenue axis. High scores here mean low budgets, but higher revenues. I then generated a scree plot in order to choose the number of principal components. Since over 80% of the variance is present in the first two PC’s, I kept 2 PC’s.
</p>
<pre class="r"><code># Plot Loadings

dr_pca$loadings[1:4, 1:2] %&gt;% as.data.frame %&gt;% rownames_to_column %&gt;% 
    ggplot() + geom_hline(aes(yintercept = 0), lty = 2) + geom_vline(aes(xintercept = 0), 
    lty = 2) + ylab(&quot;PC2&quot;) + xlab(&quot;PC1&quot;) + geom_segment(aes(x = 0, 
    y = 0, xend = Comp.1, yend = Comp.2), arrow = arrow()) + 
    geom_label(aes(x = Comp.1 * 1.1, y = Comp.2 * 1.1, label = rowname)) + 
    theme_dark()</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-15-1.png" width="768" style="display: block; margin: auto;" /></p>
<p style="color:orange">
I then computed the new dataset with PC scores for each observation. The first graph I generated was the loadings plot. In this plot, Metascore and score were the most highly correlated, having the smallest angle. Budget and gross revenue were also strongly correlated. This graph gives visualization to how variables are contributing to separating the data.
</p>
<pre class="r"><code>## PC scores plot


results &lt;- dr_pca &lt;- data.frame(PC1 = dr_pca$scores[, 1], PC2 = dr_pca$scores[, 
    2])
ggplot(dr_pca, aes(PC1, PC2)) + geom_point() + ggtitle(&quot;Principal Component Analysis (PC2 vs PC1)&quot;)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-16-1.png" width="768" style="display: block; margin: auto;" /></p>
<p style="color:orange">
This second graph plots the data onto pricipal component 1 and 2. In this graph, as you increase across the x-axis, the general popularity (score, Metascore, budget, and profit) of the movie increases. At the right of the x-axis is where you find movies like Avengers. As you move up the y-axis, budgets and revenues rise, while scores fall. The top of the y-axis is where you find movies like transformers.
</p>
<pre class="r"><code>Name &lt;- doublefeature_6$Title


dr_pca %&gt;% as.data.frame %&gt;% cbind(Name, .) %&gt;% top_n(3, PC1)  #highest on PC1</code></pre>
<pre><code>##              Name      PC1       PC2
## 1 The Dark Knight 4.400631 0.4618893
## 2          Avatar 4.410600 1.7715073
## 3     Toy Story 3 3.999228 0.3671637</code></pre>
<pre class="r"><code>dr_pca %&gt;% as.data.frame %&gt;% cbind(Name, .) %&gt;% top_n(3, wt = desc(PC1))  #lowest on PC1</code></pre>
<pre><code>##                       Name       PC1       PC2
## 1           Disaster Movie -5.361199 2.7351218
## 2                 Movie 43 -4.094684 0.9883917
## 3 The Disappointments Room -3.961450 0.9257714</code></pre>
<pre class="r"><code>dr_pca %&gt;% as.data.frame %&gt;% cbind(Name, .) %&gt;% top_n(3, wt = PC2)  #highest on PC2</code></pre>
<pre><code>##                                  Name         PC1      PC2
## 1                      Disaster Movie -5.36119888 2.735122
## 2 Transformers: Revenge of the Fallen  0.80953685 3.195637
## 3     Transformers: Age of Extinction  0.05100797 3.091391</code></pre>
<pre class="r"><code>dr_pca %&gt;% as.data.frame %&gt;% cbind(Name, .) %&gt;% top_n(3, wt = desc(PC2))  #lowest on PC2</code></pre>
<pre><code>##               Name        PC1       PC2
## 1 Relatos salvajes -0.1612754 -2.923068
## 2          Boyhood  0.8159866 -3.158763
## 3        Moonlight  0.4782156 -3.033255</code></pre>
<pre class="r"><code>doublefeature_6 %&gt;% filter(Name %in% c(&quot;The Dark Knight&quot;, &quot;Avatar&quot;, 
    &quot;Toy Story 3&quot;)) %&gt;% select(Title, gross, budget, score, Metascore)</code></pre>
<pre><code>##             Title     gross   budget score Metascore
## 1 The Dark Knight 534858444 1.85e+08   9.0        82
## 2          Avatar 760507625 2.37e+08   7.8        83
## 3     Toy Story 3 415004880 2.00e+08   8.3        92</code></pre>
<pre class="r"><code>doublefeature_6 %&gt;% filter(Name %in% c(&quot;Disaster Movie&quot;, &quot;Movie 43&quot;, 
    &quot;The Disappointments Room&quot;)) %&gt;% select(Title, gross, budget, 
    score, Metascore)</code></pre>
<pre><code>##                      Title    gross  budget score Metascore
## 1           Disaster Movie 14190901 2.0e+07   1.9        15
## 2                 Movie 43  8828771 6.0e+06   4.3        18
## 3 The Disappointments Room  2411580 1.5e+07   3.9        31</code></pre>
<p style="color:orange">
I went to the original dataset and pulled the top three and bottom three scores for each principal component. Viewing a specific movie’s information along with how it scored on the PC’s, helps visualize how these variations are being sorted out. The highest scorers on the first principal component scored well across the boards with high budgets, scores, metascores, and revenue. The lowest scores on the first PC likewise scores poorly across the boards. We even get to see Disaster Movie again, which was summarized above for scoring poorly with a 1.9/10 from the critics.
</p>
<pre class="r"><code>doublefeature_6 %&gt;% filter(Name %in% c(&quot;Transformers: Revenge of the Fallen&quot;, 
    &quot;Transformers: Age of Extinction&quot;, &quot;Disaster Movie&quot;)) %&gt;% 
    select(Title, gross, budget, score, Metascore)</code></pre>
<pre><code>##                                 Title     gross  budget score Metascore
## 1                      Disaster Movie  14190901 2.0e+07   1.9        15
## 2 Transformers: Revenge of the Fallen 402111870 2.0e+08   6.0        35
## 3     Transformers: Age of Extinction 245439076 2.1e+08   5.7        32</code></pre>
<pre class="r"><code>doublefeature_6 %&gt;% filter(Name %in% c(&quot;Relatos salvajes&quot;, &quot;Boyhood&quot;, 
    &quot;Moonlight&quot;)) %&gt;% select(Title, gross, budget, score, Title, 
    Metascore)</code></pre>
<pre><code>##              Title    gross  budget score Metascore
## 1 Relatos salvajes  3107072 3300000   8.1        77
## 2          Boyhood 25379975 4000000   7.9       100
## 3        Moonlight 27850912 1500000   7.5        99</code></pre>
<p style="color:orange">
Transformers and Boyhood being on opposite ends on PC2 demonstrates the high budget/gross revenue vs. low score aspect of this axis. Transformers: Revenge of the Fallen had a budget of 200 milion dollars, gross revenue of 402 million dollars and received scores as low as 35/100 from Metacritics. Boyhood, on the other hand, had a budget of 4 million dollars, a gross revenue of 25 million dollars, and received perfect scores from critics. Furthermore, the lowest score, Relatos salvajes had a very small budget, comparatively, but still had a high viewer score and decent Metascore. Distaster Movie’s top presence on this principal component makes sense because it had the lowest overall score, still had a high budget and gross revenue.
</p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
