<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Nina Flores" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>About Me and Computational Biology</title>
    <meta name="generator" content="Hugo 0.60.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="https://ninamflores.net/Nina_Flores_CV.pdf">VITAE</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/blog/post/">About Me and Computational Biology</a></strong>
          </h3>
        </div>
        <div class="blog-title">
         
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p style="color:#1e6330">
Every time I tell people that my major is computational biology, I’m met with blank stares as I attempt to answer their questions about this field. So, for my first post, I’ll actually <em>show</em> everyone some of what compuational biologists do.
</p>
<div id="about" class="section level1">
<h1>About</h1>
<p style="color:#1e6330">
In my Computational Biology and Bioinformatics course (SDS348), we dove into topics of data visualization, probability functions, data manipulation and wrangling, matrices, distances, associations, clustering, PCA, hypothesis testing, simulation, ANOVA, MANOVA, PERMANOVA, linear regression, logistic regression, binary classification, cross validation and regularization. All in just 16 short weeks! We spend about 70% of our time working in R, but my favorite part of the course was seeing how easily every topic we learned about was used in Python.
</p>
</div>
<div id="medical-applications" class="section level1">
<h1>Medical Applications</h1>
<p style="color:#1e6330">
In this course, we actually immersed ourselves in the biological applications of both R and Python. For example, in R: we could use data in order to predict a tumor’s malignancy.
</p>
<pre class="r"><code>library(dplyr)
library(MASS)
library(ggplot2)
library(lmtest)
data &lt;- biopsy %&gt;% transmute(clump_thickness = V1, cell_uniformity = V2, 
    marg_adhesion = V4, bland_chromatin = V7, outcome = class, 
    y = as.numeric(outcome) - 1)
head(data)</code></pre>
<pre><code>##   clump_thickness cell_uniformity marg_adhesion bland_chromatin   outcome
## 1               5               1             1               3    benign
## 2               5               4             5               3    benign
## 3               3               1             1               3    benign
## 4               6               8             1               3    benign
## 5               4               1             3               3    benign
## 6               8              10             8               9 malignant
##   y
## 1 0
## 2 0
## 3 0
## 4 0
## 5 0
## 6 1</code></pre>
<p style="color:#1e6330">
This is the <strong>biopsy</strong> dataset from Rstudio, which includes attributes of tumors recorded for 699 patients and whether they were malignant (1) or benign (0). For example, if we wanted to use the marginal adhesion score of tumors to predict its malignancy, we could do something like this:
</p>
<pre class="r"><code>fit &lt;- glm(y ~ marg_adhesion, data = data, family = binomial(link = &quot;logit&quot;))
coeftest(fit)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept)   -3.125040   0.207903 -15.031 &lt; 2.2e-16 ***
## marg_adhesion  0.965803   0.081343  11.873 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit))</code></pre>
<pre><code>##   (Intercept) marg_adhesion 
##    0.04393515    2.62689515</code></pre>
<p style="color:#1e6330">
Here, I generated a logistic regression with marginal adhesion as the explanatory variable and benign/malignancy as the response. This is telling us that every 1 unit increase in marginal adhesion, the odds of malignancy by 2.62689515. So, for a person with marginal adhesion = 10, we get log odds of -3.125040 + 0.965803 * 10 = 6.53299, or and odds of e^(6.53299) which is 687.4506 for malignancy.
</p>
<p style="color:#1e6330">
We can even add in multiple variables into the model. For example, say we have a patient whose marginal adhesion is 3 and clump thickness of their tumor is 8, we could plug them into the following model to predict if their tumor is malignant:
</p>
<pre class="r"><code>fit2 &lt;- glm(y ~ clump_thickness + marg_adhesion, family = &quot;binomial&quot;, 
    data = data)
coeftest(fit2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                  Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept)     -7.365673   0.578708 -12.7278 &lt; 2.2e-16 ***
## clump_thickness  0.907636   0.090288  10.0527 &lt; 2.2e-16 ***
## marg_adhesion    0.805301   0.085261   9.4452 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>patient1 &lt;- data.frame(clump_thickness = 8, marg_adhesion = 3)

predict(fit2, newdata = patient1, type = &quot;response&quot;)</code></pre>
<pre><code>##       1 
## 0.90981</code></pre>
<p style="color:#1e6330">
You would have to tell the patient the unfortuate news that they have a 90.1% predicted probability of malignancy.
</p>
</div>
<div id="another-biological-application" class="section level1">
<h1>Another Biological Application</h1>
<p style="color:#1e6330">
If you find predicting tumor malignancies a bit depressing, perhaps you’ll find predicting sequence alignments as more of your cup of tea. To accomplish this, I used the Needleman-Wunsch algorithm in python. I defined two sequences, and based from theirs scorings, I found a possible alignment.
</p>
<pre class="python"><code>seq1 = &quot;CCAGT&quot;
seq2 = &quot;ACAAGT&quot;

def match_fun(a,b): # Helper function to define match/mismatch scores
 if a==b:
  score=1 #match score
 else:
  score=-1 #mismatch score
 return score

def needleman(seq1,seq2,gap_penalty=-1): # Needleman-Wunsch algorithm in a funct
 m=len(seq1) #length of horizontal sequence
 n=len(seq2) #length of vertical sequence
 score=np.empty(shape=[n+1,m+1]) #array to hold scores
 for j in range(0, m + 1): score[0][j] = gap_penalty * j
 for i in range(0, n + 1): score[i][0] = gap_penalty * i
 for i in range(1, n + 1):
  for j in range(1, m + 1):
    insert = score[i - 1][j] + gap_penalty
    delete = score[i][j - 1] + gap_penalty
    match = score[i - 1][j - 1] + match_fun(seq1[j-1], seq2[i-1])
    score[i][j] = max(match, delete, insert)
 return score

import numpy as np
needleman(seq1,seq2)</code></pre>
<pre><code>## array([[ 0., -1., -2., -3., -4., -5.],
##        [-1., -1., -2., -1., -2., -3.],
##        [-2.,  0.,  0., -1., -2., -3.],
##        [-3., -1., -1.,  1.,  0., -1.],
##        [-4., -2., -2.,  0.,  0., -1.],
##        [-5., -3., -3., -1.,  1.,  0.],
##        [-6., -4., -4., -2.,  0.,  2.]])</code></pre>
<p style="color:#1e6330">
By starting at the top left corner, and choosing a path which yields the highest score, the predicted alignments ended up being:
</p>
<div id="cca-gt" class="section level2">
<h2>CCA-GT</h2>
</div>
<div id="acaagt" class="section level2">
<h2>ACAAGT</h2>
<p style="color:#1e6330">
These types of biological applications were something that I dealt with daily in my Practical Computational Biology course (BIO321G). In this course, we were tasked with predicting the secondary structure of RNA from its sequence. One of the first and most important steps of this project was to obtain an accurate sequence alignment. Here’s an example of an extended version of what I just did:
</p>
<div class="figure">
<img src="/blog/compbioexample.png" alt="The sequence alignment for the Transfer RNA (tRNA) Glutamine by helices in Jalview. The blue arrows outline the matching helices." />
<p class="caption">The sequence alignment for the Transfer RNA (tRNA) Glutamine by helices in Jalview. The blue arrows outline the matching helices.</p>
</div>
<p style="color:#1e6330">
Similar to above, an algorithm, which in this case is a comparative analysis of RNA, was used to successfully align 1,186 alignments to the reference sequence was 75 base pairs long. The regions that the blue arrows match actually form the stems of tRNA and this method of prediction helped establish the cloverleaf structure of tRNA, that I was able to also construct, from this sequence alignment. This predicted (and correct) secondary structure of Glutamine can be seen below!
</p>
<div class="figure">
<img src="/blog/Glutamineforcompbio.png" />

</div>
<p style="color:#1e6330">
So, the main takeaway from this is that prediction is an integral aspect of biology. This continually feeds my love of statistics, and is precisely the reason why I love computational biology.
</p>
</div>
</div>

              <hr>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
